# This is a basic workflow to help you get started with Actions

name: Deploy to Product
on:
  push:
    branches: [ product ]
  pull_request:
    branches: [ product ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH_PRODUCTION }}
          exclude: "[**/.**/**, .gitignore,  **/.git/**, **/node_modules/**, **/vendor/**, .editorconfig, README.md, **/src/**]"
